[package]
name = "cols"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.7"
env_logger = "0.10.0"
log = { version = "0.4.17", features = ["release_max_level_off"] }
regex = "1.8.1"
